services:
  postgres:
    image: postgres:16
    container_name: hidrocaex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hidrocaex_iot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5433:5432"
    volumes:
      - hidrocaex_postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: hidrocaex-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: hidrocaex_iot
      DB_USER: postgres
      DB_PASSWORD: toor
      API_KEY: clave-desarrollo-node-red
    ports:
      - "8080:8080"

volumes:
  hidrocaex_postgres_data: